### ISSUE TITLE
提示缺少 skynet/lualib/profile.lua

### ISSUE THREAD

**Issue by wanggan768q** [cloudwu/remotepvrtool#2]
[root@localhost remotepvrtool]# sh ./run.sh
[:00000001] LAUNCH logger 
[:00000002] LAUNCH snlua bootstrap
[:00000002] lua loader error : ...gxb/remotepvrtool/remotepvrtool/skynet/lualib/skynet.lua:9: module **'profile' not found:**
	no field package.preload['profile']
	no file '/root/gxb/remotepvrtool/remotepvrtool/skynet/lualib/profile.lua'
	no file '/root/gxb/remotepvrtool/remotepvrtool/skynet/lualib/profile/init.lua'
	no file '/root/gxb/remotepvrtool/remotepvrtool/lualib/profile.lua'
	no file '/root/gxb/remotepvrtool/remotepvrtool/skynet/luaclib/profile.so'
	no file '/root/gxb/remotepvrtool/remotepvrtool/lualib/profile.so'
stack traceback:
	[C]: in function 'require'
	...gxb/remotepvrtool/remotepvrtool/skynet/lualib/skynet.lua:9: in main chunk
	[C]: in function 'require'
	...remotepvrtool/remotepvrtool/skynet/service/bootstrap.lua:1: in local 'main'
	...gxb/remotepvrtool/remotepvrtool/skynet/lualib/loader.lua:48: in main chunk
[:00000002] KILL self

**Comment by cloudwu** [comment]
更新 skynet , profile 已改为 skynet.profile

**Comment by wanggan768q** [comment]
@cloudwu 3Q
